### ISSUE TITLE
conv_free_enclosed. for vertical plates 

### ISSUE THREAD

**Issue by jeremy-rutman** [CalebBell/ht#2]
Hi - I believe the ht.conv_free_enclosed methods  such as conv_free_enclosed.Nu_Nusselt_Rayleigh_Hollands are for horizontal plates. It's not entirely clear from the docs so that should be made clear but in any case I was wondering if there are similar methods for vertical plates? 
Thanks
Jeremy

**Comment by CalebBell** [comment]
Hi Jeremy,
Yes, those correlations are for the horizontal classic problem. I updated the documentation in the master branch to make that clearer. I also added one correlation for the vertical plate case. It will be in the next release; or you can use it by installing the master branch.
Sincerely,
Caleb

**Comment by jeremy-rutman** [comment]
ok great, thanks
