### ISSUE TITLE
NTU Method Issues

### ISSUE THREAD

**Issue by UserHandel** [CalebBell/ht#6]
First off, incredible work with this package!  I'm extremely impressed with how thorough, detailed, and well-validated it is.

I have found two errors in the NTU Method functions:

1.) The P_NTU_method function gives a divide-by-zero error if the flow rate and heat capacity of both fluids are identical in counterflow (R1 = R2 = 1).  This can be traced back to the following code in the temperature_effectiveness_basic function:

` if subtype == 'counterflow':
        # Same as TEMA 1 pass
        P1 = (1.0 - exp(-NTU1*(1 - R1)))/(1.0 - R1*exp(-NTU1*(1-R1)))
`

2. The effectiveness_NTU_method function returns an error if any of the temperatures are exactly equal to 0.  This can cause issues if you are working in Celsius or Fahrenheit rather than Kelvin.

**Comment by CalebBell** [comment]
Hi,
I can reproduce the first example. I can't reproduce the second example, please provide an example.

**Comment by UserHandel** [comment]
See the code below.  If I set Tci to -1 or 1, it converges and gives the expected result.  If I set it to 0, it fails with the following error.  This seems to fail with other subtypes such as parallel flow also.

```
line 1027, in effectiveness_NTU_method
    Tci = Tco - Q/(Cc)
UnboundLocalError: local variable 'Q' referenced before assignment

import ht
Flowh = 5
Flowc = 5
Cph = 4000
Cpc = 4000
subtype = 'counterflow'
UA = 2500
Thi = 90
Tci = 0
Results = ht.effectiveness_NTU_method(Flowh,Flowc,Cph,Cpc,subtype=subtype,UA=UA,
                                    Thi = Thi, Tci=Tci)
print(Results["Tho"],Results["Tco"])

**Comment by CalebBell** [comment]
Good catches. Thanks UserHandel!
I just release 1.0.3 with fixes for these issues.
Caleb
