### ISSUE TITLE
Documented Prandtl Number Exponent is Wrong

### ISSUE THREAD

**Issue by jrweinmeister** [CalebBell/ht#9]
The documented exponent for the Nu_horizontal_plate_turbulent_Kreith method is given as 2/3 when the correct value, and implemented value, is 1/3

https://github.com/CalebBell/ht/blob/90e0a74aa7829e9b5e989ced6033735d85db52a6/ht/conv_external.py#L792

**Comment by CalebBell** [comment]
Thanks for the heads up!
It's been fixed on the documentation website now & will be in the code next release.
